include: package:lint/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-dynamic: true
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
  exclude:
    - "lib/*.config.dart"